name: Workflow to test validity of all pull requests
on: 
  pull_request:
jobs:
    testAndBuild:
        name: Test and Build
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 12.16.1
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true            
            APP_NAME: crown-codedeploy
            DEPLOY_GROUP: prod
            S3_BUCKET_NAME: crown-prod-aws-codedeploy-deployments
            S3_FILE_NAME: staging-aws-codedeploy-${{ github.sha }}
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'

            - name: Run backend test
              run: |
                  chmod +x mvnw
                  ./mvnw -ntp clean verify -P-webpack

            - name: Inject deployment info
              run: |
                  sed -i "s/<\/footer>/\n      <div className=\"row\">Version: ${{ github.sha }} Updated: $(date)<\/div>\n<\/footer>/" src/main/webapp/app/modules/home/about.tsx

            - name: Test packaging application for prod (Also sets up Node packages)
              run: ./mvnw -ntp package -Pprod -DskipTests
