name: Workflow to deploy master branch when new commits are found
on: 
  push:
    branches:
      - master
jobs:
    buildTestAndDeploy:
        name: Build, Test and Deploy
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 12.16.1
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true            
            APP_NAME: crown-codedeploy
            DEPLOY_GROUP: prod
            S3_BUCKET_NAME: crown-prod-aws-codedeploy-deployments
            S3_FILE_NAME: staging-aws-codedeploy-${{ github.sha }}
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'

            - name: Run backend test
              run: |
                  chmod +x mvnw
                  ./mvnw -ntp clean verify -P-webpack

            - name: Inject deployment info
              run: |
                  sed -i "s/<\/footer>/\n      <div className=\"row\">Version: ${{ github.sha }} Updated: $(date)<\/div>\n<\/footer>/" src/main/webapp/app/modules/home/about.tsx

            - name: Package application for prod (Also sets up Node packages)
              run: ./mvnw -ntp package -Pprod -DskipTests


            - name: Prepare deployable
              run: |
                mkdir deployable
                cp target/crown-0.0.1-SNAPSHOT.jar deployable/
                cp appspec.yml deployable/
                cp -r scripts deployable/
            
            - name: Install AWS CLI 2
              run: |
                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                unzip awscliv2.zip
                sudo ./aws/install
                
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ca-central-1
            
            - name: AWS Deploy push
              run: |
                aws deploy push \
                --application-name ${{ env.APP_NAME }} \
                --description "This is a revision for the ${{ env.APP_NAME }}-${{ github.sha }}" \
                --ignore-hidden-files \
                --s3-location s3://${{ env.S3_BUCKET_NAME }}/${{ env.S3_FILE_NAME }}.zip \
                --source deployable/
                
            # Create deployment to CodeDeploy
            - name: AWS Create Deployment
              run: |
                aws deploy create-deployment \
                --application-name ${{ env.APP_NAME }} \
                --deployment-config-name CodeDeployDefault.OneAtATime \
                --deployment-group-name ${{ env.DEPLOY_GROUP }} \
                --file-exists-behavior OVERWRITE \
                --s3-location bucket=${{ env.S3_BUCKET_NAME }},key=${{ env.S3_FILE_NAME }}.zip,bundleType=zip \
